spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/oneutf_sys?serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: 123456
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: file:C:/Users/Administrator/Pictures/
#redis配置
  redis:
    host: 114.116.254.73
    password: 123456
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
